### ISSUE TITLE
Venue tracking system

### ISSUE THREAD

**Issue by kleinjm** [kleinjm/sparc#39]
- [ ] Track and show currently in use venues
- [ ] Track potential venues
- [ ] Track venues that are no good
- [ ] Display phone number and address for each
